# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 04:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enthusiast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enthusiast',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enthusiast', to=settings.AUTH_USER_MODEL),
        ),
    ]
